theme: jekyll-theme-minimal

title: [CV (Suvadip Batabyal)]
description: [Suvadip Batabyal is working as an Assistant Professor in the department of Computer Science and Engineering at National Institute of Technology, Durgapur, India.]
